[package]
name = "c-compiler-with-rust"
version = "0.1.0"
authors = ["watanabe <s.watanabe@sdk-co.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
